etc: Remove stack-protector c/c++ arguments
Regression introduced by:
Commit 8dfb19926e6d27cffdd24112f1d2ad156cb71968 by richard.purdie
gcc: Fix -fstack-protector issue on aarch64

srv/nas/vtec/sdk/yocto/4.2+snapshot/sysroots/x86_64-pokysdk-linux/usr/bin/aarch64-poky-linux/aarch64-poky-linux-g++ -Isrc/apps/common/libapps.a.p -Isrc/apps/common -I../src/apps/common -Iinclude -I../include -Iinclude/libcamera -I/srv/nas/vtec/sdk/yocto/4.2+snapshot/sysroots/armv8a-poky-linux//usr/src/kernels/include -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wextra -Werror -std=c++17 -O0 -g -Wno-redundant-move -Wshadow -include /srv/nfs/work/vision/libcamera/build/config.h -mcpu=cortex-a53 -march=armv8-a+crc+crypto -fstack-protector-strong -O2 -D_FORTIFY_SOURCE=0 -Wformat -Wformat-security -Werror=format-security --sysroot=/srv/nas/vtec/sdk/yocto/4.2+snapshot/sysroots/armv8a-poky-linux/ -fPIC -DHAVE_TIFF -MD -MQ src/apps/common/libapps.a.p/dng_writer.cpp.o -MF src/apps/common/libapps.a.p/dng_writer.cpp.o.d -o src/apps/common/libapps.a.p/dng_writer.cpp.o -c ../src/apps/common/dng_writer.cpp
../src/apps/common/dng_writer.cpp: In static member function ‘static int DNGWriter::write(const char*, const libcamera::Camera*, const libcamera::StreamConfiguration&, const libcamera::ControlList&, const libcamera::FrameBuffer*, const void*)’:
../src/apps/common/dng_writer.cpp:653:1: error: unrecognizable insn:
  653 | }
      | ^
(insn 4051 1692 1695 78 (parallel [
            (set (mem/c:SF (plus:DI (reg/f:DI 29 x29)
                        (const_int -260 [0xfffffffffffffefc])) [80 ccm.m[7]+0 S4 A32])
                (reg:SF 36 v4 [orig:259 _479 ] [259]))
            (set (mem/c:SF (plus:DI (reg/f:DI 29 x29)
                        (const_int -256 [0xffffffffffffff00])) [80 ccm.m[8]+0 S4 A128])
                (reg:SF 35 v3 [orig:260 _480 ] [260]))
        ]) "../src/apps/common/dng_writer.cpp":485:8 -1
     (expr_list:REG_DEAD (reg:SF 36 v4 [orig:259 _479 ] [259])
        (expr_list:REG_DEAD (reg:SF 35 v3 [orig:260 _480 ] [260])
            (nil))))
during RTL pass: cprop_hardreg
../src/apps/common/dng_writer.cpp:653:1: internal compiler error: in extract_insn, at recog.cc:2791
0x7f189aef6fb8 __libc_start_main
	???:0
Please submit a full bug report, with preprocessed source (by using -freport-bug).
Please include the complete backtrace with any bug report.
See <https://gcc.gnu.org/bugs/> for instructions.
[94/178] Compiling C++ object src/apps/lc-compliance/lc-compliance...ubprojects_googletest-release-1.11.0_googletest_src_gtest-all.cc.o
ninja: build stopped: subcommand failed.

Signed-off-by: Xavier Roumegue <xavier.roumegue@oss.nxp.com>